[database]
db = "J:\sqlite\casher.db"
conn_timeout = 5

table_debts = "debts"
table_income = "income"
table_income_payment_flow = "income_payment_flow"
table_investment_flow = "investment_flow"
table_investment_info = "investment_info"
table_item_info = "item_info"
table_payment = "payment"
table_property = "property"

